export { UserController } from './user/user.controller';
export { AuthController } from './auth/auth.controller';
export { PermissionController } from './permission/pemission.controller';
export { RoleController } from './role/role.controller';
export { ProjectController } from './project/project.controller';
export { TaskController } from './task/task.controller';
export { RolePermissionController } from './role-permission/role-permission.controller';
export { UserTaskController } from './user-task/user-task.controller';
export { TeamController } from './team/team.controller';
