version: '1.0'

services:

  # Backend service
  backend-app-1:
    build:
      context: ./task-management-system-back-end
      dockerfile: Dockerfile.dev
    container_name: task-management-system-back-end-1
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database-app
    # environment:
    #   DB_HOST: database-app  # Use service name as the database host
      # Add other environment variables as needed

  # Database service
  database-app:
    image: postgres:latest
    container_name: database-app-container-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: task-management-system-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data