# Use an official Node.js runtime as a parent image
FROM node:20.9.0-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install -g npm@10.5.1

# Expose the port that the app runs on 
EXPOSE 3000

# Define command to run your application
CMD ["npm", "run", "start"]   
