version: '1.0'

services:
  backend-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-app-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database-app
    # You can add as Optional
    # environment:
    #   # DB Host must be the database service name
    #   DB_HOST: database-app
    volumes:
      - .:/app
      - /app/node_modules

  database-app:
    image: postgres:latest
    container_name: database-app-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: task-management-system-database
    expose:
      - 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
