version: '3.8'

services:
  task-management-system-backend:
    build: .
    container_name: task-management-system-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database-service

  database-service:
    image: postgres:latest
    container_name: database-service
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    expose:
      - 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
