export const DASHBOARD_DATA_REQUEST='DASHBOARD_DATA_REQUEST';
export const DASHBOARD_DATA_SUCCESS='DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_FAILURE='DASHBOARD_DATA_FAILURE';

export const ALL_USERS_DATA_SUCCESS='ALL_USERS_DATA_SUCCESS';
export const ALL_TASKS_DATA_SUCCESS='ALL_TASKS_DATA_SUCCESS';



