export const TASK_DATA_REQUEST='TASK_DATA_REQUEST';
export const TASK_BY_ID_SUCCESS='TASK_BY_ID_SUCCESS';
export const TASK_DATA_FAILURE='TASK_DATA_FAILURE';
export const GET_ALL_TASK_DATA='GET_ALL_TASK_DATA';
export const TASK_TRANSFER_TO_DONE='TASK_TRANSFER_TO_DONE';
export const TASK_TRANSFER_TO_IN_PROGRESS='TASK_TRANSFER_TO_IN_PROGRESS';

