export const PROJECT_DATA_REQUEST='PROJECT_DATA_REQUEST';
export const PROJECT_DATA_SUCCESS='PROJECT_DATA_SUCCESS';
export const PROJECT_DATA_FAILURE='PROJECT_DATA_FAILURE';

export const ADD_PROJECT_SUCCESS='ADD_PROJECT_SUCCESS';
export const DELETE_PROJECT_BY_ID_SUCCESS='DELETE_PROJECT_BY_ID_SUCCESS';
export const UPDATE_PROJECT_BY_ID_SUCCESS='UPDATE_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID='GET_PROJECT_BY_ID';
export const ADD_TASK_TO_PROJECT='ADD_TASK_TO_PROJECT';
export const DELETE_TASK_ON_PROJECT='DELETE_TASK_ON_PROJECT';
export const ASSIGN_TASK_TO_USER='ASSIGN_TASK_TO_USER';
